#Arrays vs Lists

In [3]:
import numpy as np

In [6]:
L = [1, 2, 3]

In [7]:
A = np.array([1, 2, 3])

In [8]:
for e in L:
  print(e)

1
2
3


In [9]:
for e in A:
  print(e)

1
2
3


In [10]:
L.append(4)
print(L)

[1, 2, 3, 4]


In [11]:
A.append(4)

AttributeError: ignored

In [12]:
L + [5]

[1, 2, 3, 4, 5]

In [13]:
A + np.array([4])

array([5, 6, 7])

In [14]:
A + np.array([4, 5, 6])

array([5, 7, 9])

In [15]:
A + np.array([4, 5])

ValueError: ignored

In [16]:
2 * A

array([2, 4, 6])

In [18]:
2 * L

[1, 2, 3, 4, 1, 2, 3, 4]

In [19]:
L + L

[1, 2, 3, 4, 1, 2, 3, 4]

In [20]:
L2 = []
for e in L:
  L2.append(e + 3)

In [21]:
L2

[4, 5, 6, 7]

In [23]:
L2 = [ e + 3 for e in L]
L2

[4, 5, 6, 7]

In [24]:
L2 ** 2

TypeError: ignored

In [25]:
L2 = []
for e in L:
  L2.append(e**2)

L2

[1, 4, 9, 16]

In [26]:
A**2

array([1, 4, 9])

In [27]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [28]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [29]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [30]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

# The Dot Product
$$ a \cdot b = a^T b = \sum_{d=1}^D a_d b_d $$

In [32]:
a = np.array([1, 2])
b = np.array([3, 4])

In [33]:
dot = 0
for e, f in zip(a, b):
  dot += e * f
dot

11

In [36]:
dot = 0
for i in range(len(a)):
  dot += a[i] * b[i]
dot

11

In [37]:
a * b

array([3, 8])

In [38]:
np.sum(a*b)

11

In [39]:
(a*b).sum()

11

In [40]:
np.dot(a,b)

11

In [41]:
a.dot(b)

11

In [42]:
a @ b

11

$$ a^T b = \left\lVert a \right\rVert \left\lVert b \right\rVert \cos \theta_{ab}$$

$$ \cos \theta_{ab} = \frac{a^T b}{\left\lVert a \right\rVert \left\lVert b \right\rVert} $$

$$ \left\lVert a \right\rVert = \sqrt{\sum_{d=1}^D a_d^2 } $$

In [43]:
amag = np.sqrt((a * a).sum())
amag

2.23606797749979

In [44]:
np.linalg.norm(a)

2.23606797749979

In [45]:
cos_angle = a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))
cos_angle

0.9838699100999074

In [47]:
angle = np.arccos(cos_angle)
angle

0.17985349979247847

#Speed Test

In [48]:
from datetime import datetime

In [50]:
a = np.random.randn(100)
b = np.random.randn(100)
T = 100_000

def slow_dot_product(a, b):
  result = 0
  for e, f in zip(a, b):
    result += e * f
  return result

t0 = datetime.now()
for t in range(T):
  slow_dot_product(a, b)
dt1 = datetime.now() - t0

t0 = datetime.now()
for t in range(T):
  a.dot(b)
dt2 = datetime.now() - t0

print(dt1)
print(dt2)






0:00:02.753989
0:00:00.057518


#Matrices

In [51]:
L = [[1, 2], [3, 4]]
L

[[1, 2], [3, 4]]

In [52]:
L[0]

[1, 2]

In [53]:
L[0][1]

2

In [54]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [55]:
A[0][1]

2

In [56]:
A[0, 1]

2

In [57]:
A[:,0]

array([1, 3])

In [58]:
A.T

array([[1, 3],
       [2, 4]])

In [59]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [60]:
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [61]:
B = np.array([[1,2,3],[4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [63]:
A.dot(B.T)

ValueError: ignored

In [64]:
np.linalg.det(A)

-2.0000000000000004

In [65]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [66]:
np.linalg.inv(A).dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [67]:
np.trace(A)

5

In [68]:
A

array([[1, 2],
       [3, 4]])

In [69]:
np.diag(A)

array([1, 4])

In [70]:
np.diag([1,4])

array([[1, 0],
       [0, 4]])

In [71]:
np.linalg.eig(A)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [72]:
Lam, V = np.linalg.eig(A)

In [73]:
V[:,0] * Lam[0] == A @ V[:,0]

array([ True, False])

In [74]:
A @ V[:,0]

array([ 0.30697009, -0.21062466])

In [75]:
V[:,0] * Lam[0]

array([ 0.30697009, -0.21062466])

In [76]:
np.allclose(V[:,0] * Lam[0], A @ V[:,0])

True

# Linear Sample Problem
The ticket fee is \$1.5 for children and \$4 for adults. 2200 people bought tickets and $5055 is collected. 

In [78]:
A = np.array([[1, 1], [1.5, 4]])
b = np.array([2200, 5050])

In [79]:
np.linalg.solve(A,b)

array([1500.,  700.])

# Generation Data

In [80]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [81]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [82]:
10 * np.ones((2, 3))

array([[10., 10., 10.],
       [10., 10., 10.]])

In [83]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [84]:
np.eye(3) * 10

array([[10.,  0.,  0.],
       [ 0., 10.,  0.],
       [ 0.,  0., 10.]])

In [85]:
np.random.random()

0.6567079378538332

In [86]:
np.random.random((2,3))

array([[0.65943867, 0.40106831, 0.17237968],
       [0.34121688, 0.64534583, 0.26843547]])

In [87]:
np.random.randn(2,3)

array([[-0.34140596,  0.55981398,  0.14421329],
       [ 0.43566164, -0.26953741,  0.63121593]])

In [88]:
np.random.randn(2,3,10)

array([[[ 2.18066913,  0.5511649 ,  0.03389203,  0.76783195,
         -0.31343052,  1.09670256,  1.05166664, -0.21209979,
          0.13273518,  1.24525801],
        [-0.04491812,  0.20292146,  0.86868185, -0.6032663 ,
         -1.38458925, -0.08504172,  0.06728703, -0.72441459,
          1.0700506 ,  0.29182431],
        [ 0.53366262, -1.17255106, -1.22601338,  0.22787342,
          1.35067078, -0.92059341,  1.60943768,  0.08061344,
         -1.39812835, -0.15226383]],

       [[-0.37409857, -1.35334151,  0.50958902, -1.99401033,
         -0.71403352, -0.27014567, -1.65916349, -0.07407461,
          0.80915888,  0.23985017],
        [-0.91597843,  0.39555085,  0.4306686 ,  0.19655616,
         -0.5212528 , -1.33065064, -0.79215132, -0.41319757,
         -0.41609987,  0.03105002],
        [-0.50567479, -3.22289382,  0.5312562 , -0.33901818,
          0.51712393, -0.95637468, -1.30901237,  0.64795351,
         -1.67047305,  0.69230074]]])

In [89]:
R = np.random.randn(10000)
R.mean()

-0.0020774546865780976

In [90]:
R

array([ 0.34226403, -0.39132734,  1.88505407, ..., -0.84312045,
        0.41936536,  1.89420996])

In [91]:
np.mean(R)

-0.0020774546865780976

In [92]:
R.var()

1.0206239437786067

In [93]:
R.std()

1.0102593448113244

In [94]:
R = np.random.randn(10000,3)

In [103]:
R.mean(axis=0)

array([-0.01437063, -0.00084679, -0.01946776])

In [104]:
R.mean(axis=1)

array([ 0.49154138,  0.25948885,  0.65391034, ..., -0.7147212 ,
        0.32952063, -0.76392588])

In [105]:
R.mean(axis=1).shape

(10000,)

In [106]:
np.cov(R).shape

(10000, 10000)

In [107]:
np.cov(R.T)

array([[ 1.00301092,  0.00847361, -0.00320403],
       [ 0.00847361,  0.98679778, -0.01474766],
       [-0.00320403, -0.01474766,  0.9997277 ]])

In [108]:
np.cov(R, rowvar=False)

array([[ 1.00301092,  0.00847361, -0.00320403],
       [ 0.00847361,  0.98679778, -0.01474766],
       [-0.00320403, -0.01474766,  0.9997277 ]])

In [117]:
np.random.randint(0, 3, 3)

array([0, 0, 1])